name: mongo-sharding-repl
services:
  # сервер конфигурации
  config_srv:
    image: mongo:latest
    container_name: config_srv
    restart: always
    ports:
      - 27017:27017
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config-data:/data/db
    command: [ "--configsvr", "--replSet", "config", "--bind_ip_all", "--port", "27017" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # 1-й шард 
  shard_1:
    image: mongo:latest
    container_name: shard_1
    restart: always
    ports:
      - 27018:27018
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    volumes:
      - shard_1-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard_1", "--bind_ip_all", "--port", "27018" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # 2-й шард 
  shard_2:
    image: mongo:latest
    container_name: shard_2
    restart: always
    ports:
      - 27019:27019
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    volumes:
      - shard_2-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard_2", "--bind_ip_all", "--port", "27019" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # роутер
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    depends_on:
      - config_srv
      - shard_1
      - shard_2
    ports:
      - 27020:27020
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command: [ "mongos", "--configdb", "config/config_srv:27017", "--bind_ip_all", "--port", "27020" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: somedb
    networks:
      app-network:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  mongodb1_data_container:
  config-data:
  shard_1-data:
  shard_2-data:
