apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJVMmgyWlhSemIzWlpkWEpoT21kb2NGOUtOekZFVkVnMk1WbDRjblJzVlVaV1JXdGtSbXh6V1hwNmIyTXlXWFV4YmxORmRFND0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
